# Generated by Django 6.0.6 on 2026-07-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_alter_ataque_id_alter_estatisticas_id_alter_ficha_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='editibilidade',
            field=models.IntegerField(choices=[(0, 'Privado'), (1, 'Mestre'), (2, 'Sala'), (3, 'Pública')], default=0),
        ),
        migrations.AddField(
            model_name='ficha',
            name='visibilidade',
            field=models.IntegerField(choices=[(0, 'Privada'), (1, 'Mestre'), (2, 'Sala'), (3, 'Pública')], default=0),
        ),
    ]
