# Generated by Django 6.0.6 on 2026-08-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_ficha_editibilidade_ficha_visibilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='editibilidade',
            field=models.IntegerField(choices=[(0, 'Privada'), (1, 'Mestre'), (2, 'Sala'), (3, 'Pública')], default=0),
        ),
    ]
