# Generated by Django 6.0.6 on 2026-08-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0004_alter_ficha_editibilidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='editibilidade',
            new_name='editabilidade',
        ),
    ]
