# Generated by Django 5.2.17 on 2026-08-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0006_alter_ataque_id_alter_estatisticas_id_alter_ficha_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='foto_personagem',
            field=models.ImageField(default='img/personagem.jpg', upload_to='fichas/'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='token_personagem',
            field=models.ImageField(default='img/token.png', upload_to='fichas/'),
        ),
    ]
