# Generated by Django 5.2.17 on 2026-08-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0006_alter_ataque_id_alter_estatisticas_id_alter_ficha_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='foto_personagem',
            field=models.ImageField(default='fotos_fichas/personagem_padrao.jpg', upload_to='fotos_fichas/'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='token_personagem',
            field=models.ImageField(default='token_personagens/token_padrao.png', upload_to='token_personagens/'),
        ),
    ]
