# Generated by Django 5.2.17 on 2026-08-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0007_alter_ficha_foto_personagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='foto_personagem',
            field=models.ImageField(default='foto_personagem/personagem.jpg', upload_to='fichas/'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='token_personagem',
            field=models.ImageField(default='token_personagem/token.png', upload_to='fichas/'),
        ),
    ]
