# Generated by Django 5.2.17 on 2026-08-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0009_alter_ficha_foto_personagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='foto_personagem',
            field=models.ImageField(default='foto_personagem/personagem', upload_to='fichas/foto_personagem/'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='token_personagem',
            field=models.ImageField(default='token_personagem/token', upload_to='fichas/token_personagem/'),
        ),
    ]
