# Generated by Django 6.0.5 on 2026-05-23 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=128)),
                ('espaco', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('descricao', models.TextField(default='')),
                ('pagina', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pericia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=128)),
                ('descricao', models.TextField(default='')),
                ('pagina', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=64)),
                ('personagem', models.CharField(default='', max_length=64)),
                ('foto_personagem', models.ImageField(default='fotos_fichas/Aguiar.jpg', upload_to='fotos_fichas/')),
                ('nex', models.IntegerField(blank=True, null=True)),
                ('classe', models.CharField(default='', max_length=32)),
                ('trilha', models.CharField(default='', max_length=32)),
                ('origem', models.CharField(default='', max_length=32)),
                ('anotacoes', models.TextField(default='')),
                ('aparencia', models.TextField(default='')),
                ('historia', models.TextField(default='')),
                ('token_personagem', models.ImageField(default='token_personagens/Aguiar_corpo.png', upload_to='token_personagens/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to=settings.AUTH_USER_MODEL)),
                ('inventario', models.ManyToManyField(blank=True, to='fichas.item')),
            ],
        ),
        migrations.CreateModel(
            name='Estatisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forca', models.IntegerField(default=1)),
                ('agilidade', models.IntegerField(default=1)),
                ('vigor', models.IntegerField(default=1)),
                ('intelecto', models.IntegerField(default=1)),
                ('presenca', models.IntegerField(default=1)),
                ('pv_atual', models.IntegerField(blank=True, null=True)),
                ('pv_maximos', models.IntegerField(blank=True, null=True)),
                ('pe_atual', models.IntegerField(blank=True, null=True)),
                ('pe_maximos', models.IntegerField(blank=True, null=True)),
                ('sanidade_atual', models.IntegerField(blank=True, null=True)),
                ('sanidade_maxima', models.IntegerField(blank=True, null=True)),
                ('defesa', models.IntegerField(blank=True, null=True)),
                ('esquiva', models.IntegerField(blank=True, null=True)),
                ('bloqueio', models.IntegerField(blank=True, null=True)),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='fichas.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='Ataque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=32)),
                ('dano', models.CharField(blank=True, max_length=16, null=True)),
                ('critico', models.CharField(blank=True, max_length=16, null=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ataques', to='fichas.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=128)),
                ('descricao', models.TextField(default='')),
                ('pagina', models.CharField(default='', max_length=128)),
                ('custo', models.CharField(default='', max_length=128)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='fichas.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='TreinamentoFichaPericia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.IntegerField(blank=True, default=1, null=True)),
                ('treinamento', models.CharField(default='', max_length=32)),
                ('bonus', models.IntegerField(blank=True, default=0, null=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinamentos_pericias', to='fichas.ficha')),
                ('pericia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinamentos_pericias', to='fichas.pericia')),
            ],
        ),
        migrations.AddField(
            model_name='ficha',
            name='pericias',
            field=models.ManyToManyField(blank=True, through='fichas.TreinamentoFichaPericia', to='fichas.pericia'),
        ),
    ]
