# Generated by Django 6.0.5 on 2026-05-27 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=64)),
                ('personagem', models.CharField(default='Nome do personagem', max_length=64)),
                ('foto_personagem', models.ImageField(default='fotos_fichas/Aguiar.jpg', upload_to='fotos_fichas/')),
                ('nex', models.IntegerField(blank=True, default=40, null=True)),
                ('classe', models.CharField(default='Combatente', max_length=32)),
                ('trilha', models.CharField(default='Aniquilador', max_length=32)),
                ('origem', models.CharField(default='Acadêmico', max_length=32)),
                ('patente', models.CharField(default='Recruta', max_length=32)),
                ('anotacoes', models.TextField(default='Anotações gerais sobre o personagem e missões')),
                ('aparencia', models.TextField(default='Descrição física do personagem como: gênero, idade, altura etc.')),
                ('historia', models.TextField(default='História do personagem (de onde veio, qual seu objetivo etc.)')),
                ('token_personagem', models.ImageField(default='token_personagens/Aguiar_corpo.png', upload_to='token_personagens/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estatisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forca', models.IntegerField(default=1)),
                ('agilidade', models.IntegerField(default=1)),
                ('vigor', models.IntegerField(default=1)),
                ('intelecto', models.IntegerField(default=1)),
                ('presenca', models.IntegerField(default=1)),
                ('pv_atual', models.IntegerField(blank=True, default=0, null=True)),
                ('pv_maximos', models.IntegerField(blank=True, default=0, null=True)),
                ('pe_atual', models.IntegerField(blank=True, default=0, null=True)),
                ('pe_maximos', models.IntegerField(blank=True, default=0, null=True)),
                ('sanidade_atual', models.IntegerField(blank=True, default=0, null=True)),
                ('sanidade_maxima', models.IntegerField(blank=True, default=0, null=True)),
                ('defesa', models.IntegerField(blank=True, default=0, null=True)),
                ('esquiva', models.IntegerField(blank=True, default=0, null=True)),
                ('bloqueio', models.IntegerField(blank=True, default=0, null=True)),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='fichas.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='Ataque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Ataque', max_length=32)),
                ('dano', models.CharField(default='', max_length=16)),
                ('critico', models.CharField(default='20 x2', max_length=16)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ataques', to='fichas.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=128)),
                ('descricao', models.TextField(default='')),
                ('pagina', models.CharField(default='', max_length=128)),
                ('custo', models.CharField(default='', max_length=128)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='fichas.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_atual', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True)),
                ('carga_maxima', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True)),
                ('cat1', models.IntegerField(blank=True, default=0, null=True)),
                ('cat2', models.IntegerField(blank=True, default=0, null=True)),
                ('cat3', models.IntegerField(blank=True, default=0, null=True)),
                ('cat4', models.IntegerField(blank=True, default=0, null=True)),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='fichas.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Nome', max_length=128)),
                ('espaco', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=4, null=True)),
                ('categoria', models.CharField(default='0', max_length=32)),
                ('descricao', models.TextField(default='')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fichas.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Pericia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=128)),
                ('descricao', models.TextField(default='')),
                ('pagina', models.CharField(default='', max_length=128)),
                ('dados', models.IntegerField(blank=True, default=1, null=True)),
                ('treinamento', models.CharField(default='', max_length=32)),
                ('bonus', models.IntegerField(blank=True, default=0, null=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pericias', to='fichas.ficha')),
            ],
        ),
    ]
