# Generated by Django 6.0.5 on 2026-05-10 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('personagem', models.CharField(blank=True, max_length=128, null=True)),
                ('foto_personagem', models.ImageField(blank=True, null=True, upload_to='fotos_personagem/')),
                ('nex', models.IntegerField(blank=True, null=True)),
                ('classe', models.CharField(blank=True, max_length=128, null=True)),
                ('trilha', models.CharField(blank=True, max_length=128, null=True)),
                ('origem', models.CharField(blank=True, max_length=128, null=True)),
                ('atributos', models.JSONField(blank=True, null=True)),
                ('estatisticas', models.JSONField(blank=True, null=True)),
                ('ataques', models.JSONField(blank=True, null=True)),
                ('habilidades', models.JSONField(blank=True, null=True)),
                ('pericias', models.JSONField(blank=True, null=True)),
                ('inventario', models.JSONField(blank=True, null=True)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('token_personagem', models.ImageField(blank=True, null=True, upload_to='tokens_personagem/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
