# Generated by Django 6.0.5 on 2026-05-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='classe',
            field=models.CharField(default='Combatente', max_length=32),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='nex',
            field=models.IntegerField(blank=True, default=40, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='origem',
            field=models.CharField(default='Acadêmico', max_length=32),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='personagem',
            field=models.CharField(default='Nome do personagem', max_length=64),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='trilha',
            field=models.CharField(default='Aniquilador', max_length=32),
        ),
    ]
