# Generated by Django 6.0.5 on 2026-05-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='nome',
            field=models.CharField(default='', max_length=128),
        ),
    ]
