# Generated by Django 6.0.5 on 2026-05-24 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pagina',
        ),
    ]
