# Generated by Django 6.0.5 on 2026-05-16 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_alter_ficha_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=128)),
                ('descricao', models.TextField(default='')),
                ('pagina', models.CharField(default='', max_length=128)),
                ('custo', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=128)),
                ('espaco', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('descricao', models.TextField(default='')),
                ('pagina', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pericia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=128)),
                ('descricao', models.TextField(default='')),
                ('pagina', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='ataques',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='atributos',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='detalhes',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='estatisticas',
        ),
        migrations.AddField(
            model_name='ficha',
            name='anotacoes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ficha',
            name='aparencia',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ficha',
            name='historia',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='classe',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='foto_personagem',
            field=models.ImageField(default='fotos_fichas/Aguiar.jpg', upload_to='fotos_personagem/'),
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='habilidades',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='inventario',
        ),
        migrations.AlterField(
            model_name='ficha',
            name='nome',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='origem',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='pericias',
        ),
        migrations.AlterField(
            model_name='ficha',
            name='personagem',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='token_personagem',
            field=models.ImageField(default='tokens_fichas/Aguiar_corpo.png', upload_to='tokens_personagem/'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='trilha',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.CreateModel(
            name='Ataque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=32)),
                ('dano', models.CharField(blank=True, max_length=16, null=True)),
                ('critico', models.CharField(blank=True, max_length=16, null=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ataques', to='fichas.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='Estatisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forca', models.IntegerField(default=1)),
                ('agilidade', models.IntegerField(default=1)),
                ('vigor', models.IntegerField(default=1)),
                ('intelecto', models.IntegerField(default=1)),
                ('presenca', models.IntegerField(default=1)),
                ('pv_atual', models.IntegerField(blank=True, null=True)),
                ('pv_maximos', models.IntegerField(blank=True, null=True)),
                ('pe_atual', models.IntegerField(blank=True, null=True)),
                ('pe_maximos', models.IntegerField(blank=True, null=True)),
                ('sanidade_atual', models.IntegerField(blank=True, null=True)),
                ('sanidade_maxima', models.IntegerField(blank=True, null=True)),
                ('defesa', models.IntegerField(blank=True, null=True)),
                ('esquiva', models.IntegerField(blank=True, null=True)),
                ('bloqueio', models.IntegerField(blank=True, null=True)),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas_detalhadas', to='fichas.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='TreinamentoFichaPericia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.IntegerField(blank=True, null=True)),
                ('treinamento', models.CharField(blank=True, max_length=128, null=True)),
                ('bonus', models.IntegerField(blank=True, null=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinamentos_pericias', to='fichas.ficha')),
                ('pericia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.pericia')),
            ],
        ),
        migrations.AddField(
            model_name='ficha',
            name='habilidades',
            field=models.ManyToManyField(blank=True, to='fichas.habilidade'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='inventario',
            field=models.ManyToManyField(blank=True, to='fichas.item'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='pericias',
            field=models.ManyToManyField(blank=True, through='fichas.TreinamentoFichaPericia', to='fichas.pericia'),
        ),
    ]
