# Generated by Django 6.0.5 on 2026-05-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_alter_ficha_classe_alter_ficha_nex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='anotacoes',
            field=models.TextField(default='Anotoções gerais sobre o personagem e missões'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='aparencia',
            field=models.TextField(default='Descrição física do personagem como: genêro, idade, altura etc.'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='historia',
            field=models.TextField(default='História do personagem (de onde veio, qual seu objetivo etc.)'),
        ),
    ]
