# Generated by Django 6.0.5 on 2026-05-25 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_remove_item_pagina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='ficha',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='fichas.ficha'),
        ),
    ]
