# Generated by Django 6.0.5 on 2026-05-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_habilidade_item_pericia_remove_ficha_ataques_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='foto_personagem',
            field=models.ImageField(default='fotos_fichas/Aguiar.jpg', upload_to='fotos_fichas/'),
        ),
    ]
