# Generated by Django 6.0.5 on 2026-05-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_alter_inventario_ficha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='patente',
            field=models.CharField(default='Recruta', max_length=32),
        ),
    ]
