# Generated by Django 6.0.5 on 2026-05-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0004_alter_ficha_patente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(default='1', max_length=32),
        ),
        migrations.AlterField(
            model_name='item',
            name='espaco',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(default='Nome', max_length=128),
        ),
    ]
