# Generated by Django 6.0.5 on 2026-05-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0004_alter_ficha_foto_personagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='token_personagem',
            field=models.ImageField(default='tokens_personagens/Aguiar_corpo.png', upload_to='tokens_personagens/'),
        ),
    ]
