# Generated by Django 6.0.5 on 2026-05-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0005_alter_ficha_token_personagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='token_personagem',
            field=models.ImageField(default='token_personagens/Aguiar_corpo.png', upload_to='token_personagens/'),
        ),
    ]
