# Generated by Django 6.0.5 on 2026-05-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0005_alter_item_categoria_alter_item_espaco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
