# Generated by Django 6.0.5 on 2026-05-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0006_alter_item_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='carga_atual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='carga_maxima',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
    ]
