# Generated by Django 6.0.5 on 2026-05-17 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0006_alter_ficha_token_personagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatisticas',
            name='ficha',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='fichas.ficha'),
        ),
    ]
