# Generated by Django 6.0.5 on 2026-05-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0007_alter_inventario_carga_atual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatisticas',
            name='bloqueio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='defesa',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='esquiva',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='pe_atual',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='pe_maximos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='pv_atual',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='pv_maximos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='sanidade_atual',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='sanidade_maxima',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
