# Generated by Django 6.0.5 on 2026-05-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0008_alter_estatisticas_bloqueio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ataque',
            name='critico',
            field=models.CharField(default='20 x2', max_length=16),
        ),
        migrations.AlterField(
            model_name='ataque',
            name='dano',
            field=models.CharField(default='', max_length=16),
        ),
    ]
