# Generated by Django 6.0.5 on 2026-05-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0009_alter_ataque_id_alter_estatisticas_id_alter_ficha_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamentofichapericia',
            name='treinamento',
            field=models.CharField(default='', max_length=32),
        ),
    ]
