# Generated by Django 6.0.5 on 2026-05-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0009_alter_ataque_critico_alter_ataque_dano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ataque',
            name='nome',
            field=models.CharField(default='Ataque', max_length=32),
        ),
    ]
