# Generated by Django 6.0.6 on 2026-06-21 01:06

import django.db.models.deletion
import sessoes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fichas', '0002_alter_ataque_id_alter_estatisticas_id_alter_ficha_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=sessoes.models.gerar_codigo_unico, max_length=6, unique=True)),
                ('mestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_mestrando', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FichaSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.ficha')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_linkadas', to='sessoes.sala')),
            ],
            options={
                'unique_together': {('sala', 'jogador')},
            },
        ),
    ]
