# Generated by Django 6.0.6 on 2026-08-04 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='jogadores',
            field=models.ManyToManyField(blank=True, related_name='salas_participando', to=settings.AUTH_USER_MODEL),
        ),
    ]
