# Generated by Django 6.0.6 on 2026-08-05 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessoes', '0002_sala_jogadores'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fichasessao',
            unique_together=set(),
        ),
    ]
