# Generated by Django 6.0.5 on 2026-05-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_user_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apelido',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
